services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: devPassword42
    ports: [ "15432:5432" ]

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U botuser -d botdb -q" ]
      interval: 5s
      timeout: 3s
      retries: 5

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/001_create_user_settings.sql:/docker-entrypoint-initdb.d/001_create_user_settings.sql:ro

  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TE_TOKEN: ${TE_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL:    ${LOG_LEVEL}
      

volumes:
  db_data:
